# Generated by Django 2.0.13 on 2019-07-23 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelPlotter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dofs',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stage_name', to='ModelPlotter.Stages'),
        ),
        migrations.AlterField(
            model_name='dofs',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='type_name', to='ModelPlotter.Types'),
        ),
    ]
