# Generated by Django 2.0.13 on 2019-07-23 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ModelPlotter', '0003_auto_20190723_0419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dofs',
            old_name='dof_txt',
            new_name='dof_text',
        ),
    ]
