# Generated by Django 2.0.13 on 2019-07-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ModelPlotter', '0004_auto_20190723_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Optics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optic_text', models.CharField(max_length=4)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ModelPlotter.Types')),
            ],
        ),
    ]
