# Generated by Django 2.0.13 on 2019-07-31 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ModelPlotter', '0005_optics'),
    ]

    operations = [
        migrations.CreateModel(
            name='XMLfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=50)),
                ('t_file', models.FileField(upload_to='')),
            ],
        ),
    ]
